# Modelling NIQS Hardware

In [1]:
import numpy as np
import qiskit as qk
import matplotlib.pyplot as plt
import multiprocessing as mp
import random
import sys
from qiskit.quantum_info import DensityMatrix
from qiskit.quantum_info import Operator
from scipy.linalg import sqrtm
from tqdm.notebook import tqdm

#from src_tf_noBP import *
from src import *
np.set_printoptions(threshold=sys.maxsize)

## Strong Model Hypothesis (Same Low Rank as Target Map)

### GD

In [2]:
n = 3
d = 2**n
rank = 2

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
choi_target = ChoiMap(d, rank)
choi_model = ChoiMap(d, rank)

state_target_list = [choi_target.apply_map(state_input) for state_input in state_input_list]

model1 = ModelQuantumMap(model = choi_model,
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.5, 
                         h = 1e-4)

model1.train(num_iter = 1000, 
             use_adam = False)

0: 0.259
1: 0.507
2: 0.447
3: 0.428
4: 0.483
5: 0.354
6: 0.359
7: 0.487
8: 0.350
9: 0.484
10: 0.326
11: 0.423



KeyboardInterrupt: 

### ADAM

In [2]:
n = 3
d = 2**n
rank = 2

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
choi_target = ChoiMap(d, rank)
choi_model = ChoiMap(d, rank)

state_target_list = [choi_target.apply_map(state_input) for state_input in state_input_list]

model1 = ModelQuantumMap(model = choi_model,
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model1.train(num_iter = 1000, 
             use_adam = True)

0: fid: 0.259, c: 0.000
1: fid: 0.512, c: 0.000
2: fid: 0.410, c: 0.000
3: fid: 0.441, c: 0.000
4: fid: 0.515, c: 0.000
5: fid: 0.316, c: 0.000
6: fid: 0.383, c: 0.000
7: fid: 0.504, c: 0.000
8: fid: 0.378, c: 0.000
9: fid: 0.479, c: 0.000
10: fid: 0.309, c: 0.000
11: fid: 0.515, c: 0.000
12: fid: 0.398, c: 0.000
13: fid: 0.321, c: 0.000
14: fid: 0.401, c: 0.000
15: fid: 0.393, c: 0.000
16: fid: 0.291, c: 0.000
17: fid: 0.411, c: 0.000
18: fid: 0.416, c: 0.000
19: fid: 0.443, c: 0.000
20: fid: 0.497, c: 0.000
21: fid: 0.502, c: 0.000
22: fid: 0.277, c: 0.000
23: fid: 0.685, c: 0.000
24: fid: 0.672, c: 0.000
25: fid: 0.524, c: 0.000
26: fid: 0.480, c: 0.000
27: fid: 0.606, c: 0.000
28: fid: 0.384, c: 0.000
29: fid: 0.577, c: 0.000
30: fid: 0.499, c: 0.000
31: fid: 0.501, c: 0.000
32: fid: 0.435, c: 0.000
33: fid: 0.324, c: 0.000
34: fid: 0.581, c: 0.000
35: fid: 0.369, c: 0.000
36: fid: 0.299, c: 0.000
37: fid: 0.629, c: 0.000
38: fid: 0.480, c: 0.000
39: fid: 0.453, c: 0.000
40: fid: 0

320: fid: 0.998, c: 0.000
321: fid: 0.997, c: 0.000
322: fid: 0.996, c: 0.000
323: fid: 0.995, c: 0.000
324: fid: 0.999, c: 0.000
325: fid: 0.999, c: 0.000
326: fid: 0.997, c: 0.000
327: fid: 0.999, c: 0.000
328: fid: 0.991, c: 0.000
329: fid: 0.999, c: 0.000
330: fid: 0.999, c: 0.000
331: fid: 0.998, c: 0.000
332: fid: 1.000, c: 0.000
333: fid: 0.998, c: 0.000
334: fid: 0.998, c: 0.000
335: fid: 0.999, c: 0.000
336: fid: 0.991, c: 0.000
337: fid: 0.999, c: 0.000
338: fid: 0.997, c: 0.000
339: fid: 0.996, c: 0.000
340: fid: 0.998, c: 0.000
341: fid: 0.997, c: 0.000
342: fid: 0.992, c: 0.000
343: fid: 0.993, c: 0.000
344: fid: 0.997, c: 0.000
345: fid: 0.999, c: 0.000
346: fid: 0.999, c: 0.000
347: fid: 0.997, c: 0.000
348: fid: 0.999, c: 0.000
349: fid: 0.998, c: 0.000
350: fid: 0.998, c: 0.000
351: fid: 0.999, c: 0.000
352: fid: 1.000, c: 0.000
353: fid: 0.998, c: 0.000
354: fid: 0.996, c: 0.000
355: fid: 0.997, c: 0.000
356: fid: 0.999, c: 0.000
357: fid: 0.999, c: 0.000
358: fid: 0.

636: fid: 1.000, c: 0.000
637: fid: 1.000, c: 0.000
638: fid: 1.000, c: 0.000
639: fid: 1.000, c: 0.000
640: fid: 1.000, c: 0.000
641: fid: 1.000, c: 0.000
642: fid: 1.000, c: 0.000
643: fid: 1.000, c: 0.000
644: fid: 1.000, c: 0.000
645: fid: 1.000, c: 0.000
646: fid: 1.000, c: 0.000
647: fid: 1.000, c: 0.000
648: fid: 1.000, c: 0.000
649: fid: 1.000, c: 0.000
650: fid: 1.000, c: 0.000
651: fid: 1.000, c: 0.000
652: fid: 1.000, c: 0.000
653: fid: 1.000, c: 0.000
654: fid: 1.000, c: 0.000
655: fid: 1.000, c: 0.000
656: fid: 1.000, c: 0.000
657: fid: 1.000, c: 0.000
658: fid: 1.000, c: 0.000
659: fid: 1.000, c: 0.000
660: fid: 1.000, c: 0.000
661: fid: 1.000, c: 0.000
662: fid: 1.000, c: 0.000
663: fid: 1.000, c: 0.000
664: fid: 1.000, c: 0.000
665: fid: 1.000, c: 0.000
666: fid: 1.000, c: 0.000
667: fid: 1.000, c: 0.000
668: fid: 1.000, c: 0.000
669: fid: 1.000, c: 0.000
670: fid: 1.000, c: 0.000
671: fid: 1.000, c: 0.000
672: fid: 1.000, c: 0.000
673: fid: 1.000, c: 0.000
674: fid: 1.

KeyboardInterrupt: 

In [ ]:
fig=plt.figure(figsize=(6,4), dpi = 130, facecolor='w', edgecolor='k')
plt.plot(model1.fid_list)
plt.plot(model2.fid_list)
plt.xlabel("Iteration")
plt.ylabel("Fidelity")
plt.legend(["GD", "ADAM"])
plt.grid()
plt.show()

### Compare Target Quantum Map to Fitted Models with a Random Pure state

In [ ]:
for i in range(5):

    state_random = generate_state(d, 1)
    state_target = apply_map(state_random, choi_target)

    choi_model1 = generate_choi(model1.X_model)
    state_model1 = apply_map(state_random, choi_model1)
    print(state_fidelity(state_model1, state_target))

    choi_model2 = generate_choi(model2.X_model)
    state_model2 = apply_map(state_random, choi_model2)
    print(state_fidelity(state_model2, state_target))
    print("----")

## More Testing

### Full Rank Model (No Target Hypothesis)

In [ ]:
n = 3
d = 2**n

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
X_target = generate_ginibre(d**2, 2)
choi_target = generate_choi(X_target)
state_target_list = [apply_map(state_input, choi_target) for state_input in state_input_list]

model3 = ModelQuantumMap(n = 3, 
                         rank = d**2, 
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model3.train(num_iter = 1000, 
             use_adam = True)

### Over-Constrained Model

In [ ]:
n = 3
d = 2**n

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
X_target = generate_ginibre(d**2, 4)
choi_target = generate_choi(X_target)
state_target_list = [apply_map(state_input, choi_target) for state_input in state_input_list]

model4 = ModelQuantumMap(n = 3, 
                         rank = 2, 
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model4.train(num_iter = 1000, 
             use_adam = True)

### Full Rank Target

In [ ]:
n = 3
d = 2**n

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
X_target = generate_ginibre(d**2, d**2)
choi_target = generate_choi(X_target)
state_target_list = [apply_map(state_input, choi_target) for state_input in state_input_list]


model5 = ModelQuantumMap(n = 3, 
                         rank = d**2, 
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model5.train(num_iter = 1000, 
             use_adam = True)

In [ ]:
np.mean((choi_target - choi_model1)**2)

fig=plt.figure(figsize=(6,4), dpi = 130, facecolor='w', edgecolor='k')
plt.plot(model3.fid_list)
plt.plot(model4.fid_list)
plt.plot(model5.fid_list)
plt.xlabel("Iteration")
plt.ylabel("Fidelity")
plt.legend(["Full Rank Model", "Over-Contrained", "Full Rank Target"])
plt.grid()
plt.show()

### Four Qubits

In [ ]:
n = 4
d = 2**n

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
X_target = generate_ginibre(d**2, 6)
choi_target = generate_choi(X_target)
state_target_list = [apply_map(state_input, choi_target) for state_input in state_input_list]


model6 = ModelQuantumMap(n = 4, 
                         rank = 6, 
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model6.train(num_iter = 2000, 
             use_adam = True)

## Constrained Inputs

In [ ]:
n = 3
d = 2**n

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]
random.shuffle(state_input_list)
state_input_list = state_input_list[:100]


np.random.seed(42)
X_target = generate_ginibre(d**2, 4)
choi_target = generate_choi(X_target)
state_target_list = [apply_map(state_input, choi_target) for state_input in state_input_list]


model6 = ModelQuantumMap(n = 3, 
                         rank = 4, 
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model6.train(num_iter = 1000, 
             use_adam = True)

In [ ]:
for i in range(5):

    state_random = generate_state(d, 1)
    state_target = apply_map(state_random, choi_target)

    choi_model6 = generate_choi(model6.X_model)
    state_model6 = apply_map(state_random, choi_model6)
    print(state_fidelity(state_model6, state_target))
    print("----")

In [ ]:
n = 3
d = 2**n

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]
random.shuffle(state_input_list)
state_input_list = state_input_list[:50]


np.random.seed(42)
X_target = generate_ginibre(d**2, 4)
choi_target = generate_choi(X_target)
state_target_list = [apply_map(state_input, choi_target) for state_input in state_input_list]


model6 = ModelQuantumMap(n = 3, 
                         rank = 4, 
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model6.train(num_iter = 1000, 
             use_adam = True)

In [ ]:
for i in range(5):

    state_random = generate_state(d, 1)
    state_target = apply_map(state_random, choi_target)

    choi_model6 = generate_choi(model6.X_model)
    state_model6 = apply_map(state_random, choi_model6)
    print(state_fidelity(state_model6, state_target))
    print("----")

In [ ]:
n = 3
d = 2**n

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]
random.shuffle(state_input_list)
state_input_list = state_input_list[:25]


np.random.seed(42)
X_target = generate_ginibre(d**2, 4)
choi_target = generate_choi(X_target)
state_target_list = [apply_map(state_input, choi_target) for state_input in state_input_list]


model6 = ModelQuantumMap(n = 3, 
                         rank = 4, 
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model6.train(num_iter = 1000, 
             use_adam = True)

In [ ]:
for i in range(5):

    state_random = generate_state(d, 1)
    state_target = apply_map(state_random, choi_target)

    choi_model6 = generate_choi(model6.X_model)
    state_model6 = apply_map(state_random, choi_model6)
    print(state_fidelity(state_model6, state_target))
    print("----")

In [ ]:
n = 3
d = 2**n

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]
random.shuffle(state_input_list)
state_input_list = state_input_list[:10]


np.random.seed(42)
X_target = generate_ginibre(d**2, 4)
choi_target = generate_choi(X_target)
state_target_list = [apply_map(state_input, choi_target) for state_input in state_input_list]


model6 = ModelQuantumMap(n = 3, 
                         rank = 4, 
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model6.train(num_iter = 1000, 
             use_adam = True)

In [ ]:
for i in range(5):

    state_random = generate_state(d, 1)
    state_target = apply_map(state_random, choi_target)

    choi_model6 = generate_choi(model6.X_model)
    state_model6 = apply_map(state_random, choi_model6)
    print(state_fidelity(state_model6, state_target))
    print("----")

## 4 Qubits

In [ ]:
n = 4
d = 2**n

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]
random.shuffle(state_input_list)
state_input_list = state_input_list[:100]


np.random.seed(42)
X_target = generate_ginibre(d**2, 4)
choi_target = generate_choi(X_target)
state_target_list = [apply_map(state_input, choi_target) for state_input in state_input_list]


model6 = ModelQuantumMap(n = 4, 
                         rank = 4, 
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model6.train(num_iter = 1000, 
             use_adam = True)

In [ ]:
for i in range(5):

    state_random = generate_state(d, 1)
    state_target = apply_map(state_random, choi_target)

    choi_model6 = generate_choi(model6.X_model)
    state_model6 = apply_map(state_random, choi_model6)
    print(state_fidelity(state_model6, state_target))
    print("----")

## Kraus Form

In [4]:
n = 3
d = 2**n

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
X, _, _ = generate_ginibre(d, d)
U = generate_unitary(X)
kraus_target = KrausMap(U, c = 0.6, d = d, rank = 2)
kraus_model = KrausMap(U, c = 0.1, d = d, rank = 2)

state_target_list = [kraus_target.apply_map(state_input) for state_input in state_input_list]

model1 = ModelQuantumMap(model = kraus_model,
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model1.train(num_iter = 2000, 
             use_adam = True)

0: fid: 0.483, c: 0.105
1: fid: 0.695, c: 0.109
2: fid: 0.647, c: 0.114
3: fid: 0.630, c: 0.119
4: fid: 0.598, c: 0.124
5: fid: 0.555, c: 0.130
6: fid: 0.423, c: 0.136
7: fid: 0.611, c: 0.142
8: fid: 0.595, c: 0.148
9: fid: 0.538, c: 0.154
10: fid: 0.694, c: 0.161
11: fid: 0.625, c: 0.168
12: fid: 0.679, c: 0.175
13: fid: 0.814, c: 0.183
14: fid: 0.638, c: 0.190
15: fid: 0.608, c: 0.198
16: fid: 0.665, c: 0.206
17: fid: 0.693, c: 0.214
18: fid: 0.607, c: 0.223
19: fid: 0.730, c: 0.232
20: fid: 0.656, c: 0.241
21: fid: 0.591, c: 0.251
22: fid: 0.776, c: 0.261
23: fid: 0.622, c: 0.271
24: fid: 0.776, c: 0.282
25: fid: 0.740, c: 0.293
26: fid: 0.739, c: 0.304
27: fid: 0.709, c: 0.315
28: fid: 0.720, c: 0.326
29: fid: 0.778, c: 0.338
30: fid: 0.736, c: 0.349
31: fid: 0.850, c: 0.361
32: fid: 0.704, c: 0.373
33: fid: 0.741, c: 0.385
34: fid: 0.720, c: 0.397
35: fid: 0.768, c: 0.409
36: fid: 0.859, c: 0.421
37: fid: 0.786, c: 0.433
38: fid: 0.826, c: 0.445
39: fid: 0.775, c: 0.457
40: fid: 0

322: fid: 0.987, c: 0.607
323: fid: 0.991, c: 0.607
324: fid: 0.990, c: 0.607
325: fid: 0.996, c: 0.608
326: fid: 0.993, c: 0.607
327: fid: 0.996, c: 0.607
328: fid: 0.998, c: 0.607
329: fid: 0.997, c: 0.607
330: fid: 0.996, c: 0.607
331: fid: 0.995, c: 0.606
332: fid: 0.997, c: 0.606
333: fid: 0.996, c: 0.606
334: fid: 0.999, c: 0.605
335: fid: 0.997, c: 0.605
336: fid: 0.998, c: 0.605
337: fid: 0.998, c: 0.605
338: fid: 0.997, c: 0.604
339: fid: 0.999, c: 0.604
340: fid: 0.994, c: 0.603
341: fid: 0.997, c: 0.603
342: fid: 0.997, c: 0.603
343: fid: 0.997, c: 0.603
344: fid: 0.995, c: 0.602
345: fid: 0.996, c: 0.602
346: fid: 0.996, c: 0.602
347: fid: 0.998, c: 0.602
348: fid: 0.996, c: 0.602
349: fid: 0.997, c: 0.601
350: fid: 0.997, c: 0.601
351: fid: 0.996, c: 0.601
352: fid: 0.999, c: 0.601
353: fid: 0.997, c: 0.601
354: fid: 0.998, c: 0.601
355: fid: 0.994, c: 0.601
356: fid: 0.997, c: 0.601
357: fid: 0.996, c: 0.601
358: fid: 0.997, c: 0.601
359: fid: 0.998, c: 0.602
360: fid: 0.

637: fid: 1.000, c: 0.599
638: fid: 1.000, c: 0.599
639: fid: 1.000, c: 0.599
640: fid: 1.000, c: 0.599
641: fid: 1.000, c: 0.599
642: fid: 1.000, c: 0.600
643: fid: 1.000, c: 0.600
644: fid: 1.000, c: 0.600
645: fid: 1.000, c: 0.600
646: fid: 1.000, c: 0.600
647: fid: 1.000, c: 0.600
648: fid: 1.000, c: 0.600
649: fid: 1.000, c: 0.600
650: fid: 1.000, c: 0.600
651: fid: 1.000, c: 0.600
652: fid: 1.000, c: 0.600
653: fid: 1.000, c: 0.600
654: fid: 1.000, c: 0.600
655: fid: 1.000, c: 0.600
656: fid: 1.000, c: 0.600
657: fid: 1.000, c: 0.600
658: fid: 1.000, c: 0.600
659: fid: 1.000, c: 0.600
660: fid: 1.000, c: 0.600
661: fid: 1.000, c: 0.600
662: fid: 1.000, c: 0.600
663: fid: 1.000, c: 0.600
664: fid: 1.000, c: 0.600
665: fid: 1.000, c: 0.600
666: fid: 1.000, c: 0.600
667: fid: 1.000, c: 0.600
668: fid: 1.000, c: 0.600
669: fid: 1.000, c: 0.600
670: fid: 1.000, c: 0.600
671: fid: 1.000, c: 0.600
672: fid: 1.000, c: 0.600
673: fid: 1.000, c: 0.600
674: fid: 1.000, c: 0.600
675: fid: 1.

953: fid: 1.000, c: 0.600
954: fid: 1.000, c: 0.600
955: fid: 1.000, c: 0.600
956: fid: 1.000, c: 0.600
957: fid: 1.000, c: 0.600
958: fid: 1.000, c: 0.600
959: fid: 1.000, c: 0.600
960: fid: 1.000, c: 0.600
961: fid: 1.000, c: 0.600
962: fid: 1.000, c: 0.600
963: fid: 1.000, c: 0.600
964: fid: 1.000, c: 0.600
965: fid: 1.000, c: 0.600
966: fid: 1.000, c: 0.600
967: fid: 1.000, c: 0.600
968: fid: 1.000, c: 0.600
969: fid: 1.000, c: 0.600
970: fid: 1.000, c: 0.600
971: fid: 1.000, c: 0.600
972: fid: 1.000, c: 0.600
973: fid: 1.000, c: 0.600
974: fid: 1.000, c: 0.600
975: fid: 1.000, c: 0.600
976: fid: 1.000, c: 0.600
977: fid: 1.000, c: 0.600
978: fid: 1.000, c: 0.600
979: fid: 1.000, c: 0.600
980: fid: 1.000, c: 0.600
981: fid: 1.000, c: 0.600
982: fid: 1.000, c: 0.600
983: fid: 1.000, c: 0.600
984: fid: 1.000, c: 0.600
985: fid: 1.000, c: 0.600
986: fid: 1.000, c: 0.600
987: fid: 1.000, c: 0.600
988: fid: 1.000, c: 0.600
989: fid: 1.000, c: 0.600
990: fid: 1.000, c: 0.600
991: fid: 1.

1259: fid: 1.000, c: 0.600
1260: fid: 1.000, c: 0.600
1261: fid: 1.000, c: 0.600
1262: fid: 1.000, c: 0.600
1263: fid: 1.000, c: 0.600
1264: fid: 1.000, c: 0.600
1265: fid: 1.000, c: 0.600
1266: fid: 1.000, c: 0.600
1267: fid: 1.000, c: 0.600
1268: fid: 1.000, c: 0.600
1269: fid: 1.000, c: 0.600
1270: fid: 1.000, c: 0.600
1271: fid: 1.000, c: 0.600
1272: fid: 1.000, c: 0.600
1273: fid: 1.000, c: 0.600
1274: fid: 1.000, c: 0.600
1275: fid: 1.000, c: 0.600
1276: fid: 1.000, c: 0.600
1277: fid: 1.000, c: 0.600
1278: fid: 1.000, c: 0.600
1279: fid: 1.000, c: 0.600
1280: fid: 1.000, c: 0.600
1281: fid: 1.000, c: 0.600
1282: fid: 1.000, c: 0.600
1283: fid: 1.000, c: 0.600
1284: fid: 1.000, c: 0.600
1285: fid: 1.000, c: 0.600
1286: fid: 1.000, c: 0.600
1287: fid: 1.000, c: 0.600
1288: fid: 1.000, c: 0.600
1289: fid: 1.000, c: 0.600
1290: fid: 1.000, c: 0.600
1291: fid: 1.000, c: 0.600
1292: fid: 1.000, c: 0.600
1293: fid: 1.000, c: 0.600
1294: fid: 1.000, c: 0.600
1295: fid: 1.000, c: 0.600
1

1564: fid: 1.000, c: 0.600
1565: fid: 1.000, c: 0.600
1566: fid: 1.000, c: 0.600
1567: fid: 1.000, c: 0.600
1568: fid: 1.000, c: 0.600
1569: fid: 1.000, c: 0.600
1570: fid: 1.000, c: 0.600
1571: fid: 1.000, c: 0.600
1572: fid: 1.000, c: 0.600
1573: fid: 1.000, c: 0.600
1574: fid: 1.000, c: 0.600
1575: fid: 1.000, c: 0.600
1576: fid: 1.000, c: 0.600
1577: fid: 1.000, c: 0.600
1578: fid: 1.000, c: 0.600
1579: fid: 1.000, c: 0.600
1580: fid: 1.000, c: 0.600
1581: fid: 1.000, c: 0.600
1582: fid: 1.000, c: 0.600
1583: fid: 1.000, c: 0.600
1584: fid: 1.000, c: 0.600
1585: fid: 1.000, c: 0.600
1586: fid: 1.000, c: 0.600
1587: fid: 1.000, c: 0.600
1588: fid: 1.000, c: 0.600
1589: fid: 1.000, c: 0.600
1590: fid: 1.000, c: 0.600
1591: fid: 1.000, c: 0.600
1592: fid: 1.000, c: 0.600
1593: fid: 1.000, c: 0.600
1594: fid: 1.000, c: 0.600
1595: fid: 1.000, c: 0.600
1596: fid: 1.000, c: 0.600
1597: fid: 1.000, c: 0.600
1598: fid: 1.000, c: 0.600
1599: fid: 1.000, c: 0.600
1600: fid: 1.000, c: 0.600
1

1869: fid: 1.000, c: 0.600
1870: fid: 1.000, c: 0.600
1871: fid: 1.000, c: 0.600
1872: fid: 1.000, c: 0.600
1873: fid: 1.000, c: 0.600
1874: fid: 1.000, c: 0.600
1875: fid: 1.000, c: 0.600
1876: fid: 1.000, c: 0.600
1877: fid: 1.000, c: 0.600
1878: fid: 1.000, c: 0.600
1879: fid: 1.000, c: 0.600
1880: fid: 1.000, c: 0.600
1881: fid: 1.000, c: 0.600
1882: fid: 1.000, c: 0.600
1883: fid: 1.000, c: 0.600
1884: fid: 1.000, c: 0.600
1885: fid: 1.000, c: 0.600
1886: fid: 1.000, c: 0.600
1887: fid: 1.000, c: 0.600
1888: fid: 1.000, c: 0.600
1889: fid: 1.000, c: 0.600
1890: fid: 1.000, c: 0.600
1891: fid: 1.000, c: 0.600
1892: fid: 1.000, c: 0.600
1893: fid: 1.000, c: 0.600
1894: fid: 1.000, c: 0.600
1895: fid: 1.000, c: 0.600
1896: fid: 1.000, c: 0.600
1897: fid: 1.000, c: 0.600
1898: fid: 1.000, c: 0.600
1899: fid: 1.000, c: 0.600
1900: fid: 1.000, c: 0.600
1901: fid: 1.000, c: 0.600
1902: fid: 1.000, c: 0.600
1903: fid: 1.000, c: 0.600
1904: fid: 1.000, c: 0.600
1905: fid: 1.000, c: 0.600
1

In [9]:
n = 3
d = 2**n

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
X = generate_ginibre(d, d)
U = generate_unitary(X)
kraus_target = KrausMap(U, 0.7, d, 2)
kraus_model = KrausMap(U, 0.1, d, d**2)

state_target_list = [kraus_target.apply_map(state_input) for state_input in state_input_list]

model2 = ModelQuantumMap(model = kraus_model,
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model2.train(num_iter = 2000, 
             use_adam = True)

0: fid: 0.643, c: 0.105
1: fid: 0.640, c: 0.109
2: fid: 0.650, c: 0.114
3: fid: 0.637, c: 0.120
4: fid: 0.645, c: 0.125
5: fid: 0.630, c: 0.131
6: fid: 0.662, c: 0.136
7: fid: 0.670, c: 0.142
8: fid: 0.689, c: 0.149
9: fid: 0.657, c: 0.155
10: fid: 0.717, c: 0.162
11: fid: 0.667, c: 0.169
12: fid: 0.746, c: 0.176
13: fid: 0.711, c: 0.184
14: fid: 0.701, c: 0.192
15: fid: 0.725, c: 0.200
16: fid: 0.689, c: 0.208
17: fid: 0.684, c: 0.217
18: fid: 0.707, c: 0.226
19: fid: 0.711, c: 0.235
20: fid: 0.726, c: 0.245
21: fid: 0.729, c: 0.255
22: fid: 0.757, c: 0.265
23: fid: 0.767, c: 0.276
24: fid: 0.745, c: 0.286
25: fid: 0.742, c: 0.298
26: fid: 0.789, c: 0.309
27: fid: 0.742, c: 0.320
28: fid: 0.750, c: 0.332
29: fid: 0.791, c: 0.344
30: fid: 0.869, c: 0.356
31: fid: 0.794, c: 0.368
32: fid: 0.797, c: 0.380
33: fid: 0.790, c: 0.393
34: fid: 0.811, c: 0.405
35: fid: 0.799, c: 0.418
36: fid: 0.810, c: 0.431
37: fid: 0.835, c: 0.443
38: fid: 0.842, c: 0.456
39: fid: 0.818, c: 0.468
40: fid: 0

320: fid: 0.989, c: 0.705
321: fid: 0.987, c: 0.705
322: fid: 0.988, c: 0.705
323: fid: 0.985, c: 0.705
324: fid: 0.988, c: 0.705
325: fid: 0.985, c: 0.705
326: fid: 0.982, c: 0.705
327: fid: 0.989, c: 0.705
328: fid: 0.986, c: 0.705
329: fid: 0.986, c: 0.705
330: fid: 0.989, c: 0.706
331: fid: 0.979, c: 0.706
332: fid: 0.989, c: 0.706
333: fid: 0.991, c: 0.706
334: fid: 0.988, c: 0.707
335: fid: 0.991, c: 0.707
336: fid: 0.991, c: 0.707
337: fid: 0.986, c: 0.707
338: fid: 0.989, c: 0.707
339: fid: 0.986, c: 0.707
340: fid: 0.988, c: 0.707
341: fid: 0.985, c: 0.707
342: fid: 0.990, c: 0.707
343: fid: 0.990, c: 0.707
344: fid: 0.987, c: 0.707
345: fid: 0.994, c: 0.707
346: fid: 0.990, c: 0.707
347: fid: 0.989, c: 0.707
348: fid: 0.989, c: 0.706
349: fid: 0.993, c: 0.706
350: fid: 0.992, c: 0.706
351: fid: 0.993, c: 0.705
352: fid: 0.994, c: 0.705
353: fid: 0.991, c: 0.705
354: fid: 0.993, c: 0.704
355: fid: 0.991, c: 0.704
356: fid: 0.989, c: 0.703
357: fid: 0.991, c: 0.703
358: fid: 0.

636: fid: 0.999, c: 0.691
637: fid: 0.999, c: 0.690
638: fid: 0.997, c: 0.690
639: fid: 0.997, c: 0.690
640: fid: 0.996, c: 0.690
641: fid: 0.997, c: 0.690
642: fid: 0.999, c: 0.690
643: fid: 0.998, c: 0.690
644: fid: 0.999, c: 0.690
645: fid: 0.999, c: 0.690
646: fid: 0.997, c: 0.689
647: fid: 0.999, c: 0.689
648: fid: 0.993, c: 0.689
649: fid: 0.999, c: 0.689
650: fid: 0.997, c: 0.689
651: fid: 0.995, c: 0.689
652: fid: 0.998, c: 0.689
653: fid: 0.999, c: 0.689
654: fid: 0.997, c: 0.689
655: fid: 0.998, c: 0.688
656: fid: 0.996, c: 0.688
657: fid: 0.999, c: 0.688
658: fid: 0.999, c: 0.688
659: fid: 0.996, c: 0.688
660: fid: 0.998, c: 0.688
661: fid: 0.999, c: 0.688
662: fid: 0.998, c: 0.688
663: fid: 0.999, c: 0.688
664: fid: 0.999, c: 0.688
665: fid: 0.999, c: 0.688
666: fid: 0.997, c: 0.688
667: fid: 0.998, c: 0.688
668: fid: 0.994, c: 0.688
669: fid: 0.997, c: 0.688
670: fid: 0.999, c: 0.687
671: fid: 0.999, c: 0.687
672: fid: 0.996, c: 0.687
673: fid: 0.994, c: 0.688
674: fid: 0.

952: fid: 0.998, c: 0.683
953: fid: 0.999, c: 0.683
954: fid: 0.999, c: 0.684
955: fid: 0.999, c: 0.684
956: fid: 0.999, c: 0.684
957: fid: 0.999, c: 0.684
958: fid: 0.999, c: 0.684
959: fid: 0.999, c: 0.684
960: fid: 0.999, c: 0.684
961: fid: 0.999, c: 0.684
962: fid: 0.998, c: 0.684
963: fid: 0.999, c: 0.684
964: fid: 0.999, c: 0.685
965: fid: 0.999, c: 0.685
966: fid: 0.999, c: 0.685
967: fid: 0.999, c: 0.685
968: fid: 0.999, c: 0.685
969: fid: 0.999, c: 0.684
970: fid: 0.999, c: 0.684
971: fid: 0.999, c: 0.684
972: fid: 0.999, c: 0.684
973: fid: 0.999, c: 0.684
974: fid: 0.999, c: 0.684
975: fid: 0.999, c: 0.684
976: fid: 0.999, c: 0.684
977: fid: 0.999, c: 0.684
978: fid: 0.999, c: 0.684
979: fid: 0.999, c: 0.684
980: fid: 0.999, c: 0.684
981: fid: 0.999, c: 0.684
982: fid: 0.999, c: 0.684
983: fid: 0.999, c: 0.684
984: fid: 0.999, c: 0.684
985: fid: 0.999, c: 0.684
986: fid: 0.999, c: 0.684
987: fid: 0.999, c: 0.684
988: fid: 0.999, c: 0.684
989: fid: 0.999, c: 0.684
990: fid: 0.

1258: fid: 0.999, c: 0.689
1259: fid: 0.999, c: 0.689
1260: fid: 0.997, c: 0.689
1261: fid: 0.999, c: 0.689
1262: fid: 0.999, c: 0.689
1263: fid: 0.993, c: 0.689
1264: fid: 0.992, c: 0.690
1265: fid: 0.998, c: 0.690
1266: fid: 0.999, c: 0.690
1267: fid: 0.999, c: 0.690
1268: fid: 0.999, c: 0.690
1269: fid: 0.996, c: 0.690
1270: fid: 0.998, c: 0.690
1271: fid: 0.999, c: 0.690
1272: fid: 0.995, c: 0.690
1273: fid: 0.987, c: 0.691
1274: fid: 0.999, c: 0.691
1275: fid: 0.996, c: 0.692
1276: fid: 0.998, c: 0.692
1277: fid: 0.998, c: 0.692
1278: fid: 0.999, c: 0.692
1279: fid: 0.998, c: 0.692
1280: fid: 0.999, c: 0.692
1281: fid: 0.996, c: 0.692
1282: fid: 0.999, c: 0.692
1283: fid: 0.999, c: 0.692
1284: fid: 0.997, c: 0.692
1285: fid: 0.999, c: 0.692
1286: fid: 0.997, c: 0.691
1287: fid: 0.997, c: 0.691
1288: fid: 0.996, c: 0.691
1289: fid: 0.996, c: 0.691
1290: fid: 0.999, c: 0.691
1291: fid: 0.998, c: 0.690
1292: fid: 0.999, c: 0.690
1293: fid: 0.999, c: 0.690
1294: fid: 0.997, c: 0.690
1

1562: fid: 0.999, c: 0.689
1563: fid: 0.999, c: 0.689
1564: fid: 0.999, c: 0.689
1565: fid: 0.999, c: 0.689
1566: fid: 0.999, c: 0.689
1567: fid: 0.999, c: 0.689
1568: fid: 0.999, c: 0.689
1569: fid: 0.999, c: 0.689
1570: fid: 0.999, c: 0.689
1571: fid: 0.999, c: 0.689
1572: fid: 0.999, c: 0.689
1573: fid: 0.999, c: 0.689
1574: fid: 0.999, c: 0.689
1575: fid: 0.999, c: 0.689
1576: fid: 0.999, c: 0.689
1577: fid: 0.999, c: 0.689
1578: fid: 0.999, c: 0.689
1579: fid: 0.999, c: 0.689
1580: fid: 0.999, c: 0.689
1581: fid: 0.999, c: 0.689
1582: fid: 0.999, c: 0.689
1583: fid: 0.999, c: 0.689
1584: fid: 0.999, c: 0.689
1585: fid: 0.999, c: 0.689
1586: fid: 0.999, c: 0.689
1587: fid: 0.999, c: 0.689
1588: fid: 0.999, c: 0.689
1589: fid: 0.999, c: 0.689
1590: fid: 0.999, c: 0.689
1591: fid: 0.999, c: 0.689
1592: fid: 0.999, c: 0.689
1593: fid: 0.999, c: 0.689
1594: fid: 0.999, c: 0.689
1595: fid: 0.999, c: 0.689
1596: fid: 0.999, c: 0.689
1597: fid: 0.999, c: 0.689
1598: fid: 0.999, c: 0.689
1

1866: fid: 0.999, c: 0.688
1867: fid: 0.998, c: 0.688
1868: fid: 0.998, c: 0.688
1869: fid: 0.999, c: 0.688
1870: fid: 0.999, c: 0.688
1871: fid: 0.998, c: 0.688
1872: fid: 0.997, c: 0.688
1873: fid: 0.997, c: 0.688
1874: fid: 0.999, c: 0.688
1875: fid: 0.999, c: 0.688
1876: fid: 0.998, c: 0.689
1877: fid: 0.998, c: 0.689
1878: fid: 0.998, c: 0.689
1879: fid: 0.998, c: 0.689
1880: fid: 0.999, c: 0.689
1881: fid: 0.999, c: 0.690
1882: fid: 0.999, c: 0.690
1883: fid: 0.998, c: 0.690
1884: fid: 0.999, c: 0.690
1885: fid: 0.998, c: 0.689
1886: fid: 0.999, c: 0.689
1887: fid: 0.998, c: 0.689
1888: fid: 0.999, c: 0.689
1889: fid: 0.999, c: 0.689
1890: fid: 0.999, c: 0.688
1891: fid: 0.998, c: 0.688
1892: fid: 0.999, c: 0.687
1893: fid: 0.998, c: 0.687
1894: fid: 0.999, c: 0.687
1895: fid: 0.999, c: 0.687
1896: fid: 0.998, c: 0.687
1897: fid: 0.999, c: 0.687
1898: fid: 0.998, c: 0.686
1899: fid: 0.999, c: 0.686
1900: fid: 0.999, c: 0.686
1901: fid: 0.999, c: 0.686
1902: fid: 0.999, c: 0.686
1

### Five Qubits, Low Rank

In [6]:
n = 5
d = 2**n
rank = 2

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
X = generate_ginibre(d, d)
U = generate_unitary(X)
kraus_target = KrausMap(U, 0.7, d, rank)
kraus_model = KrausMap(U, 0.1, d, rank)

state_target_list = [kraus_target.apply_map(state_input) for state_input in state_input_list]

model3 = ModelQuantumMap(model = kraus_model,
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model3.train(num_iter = 2000, 
             use_adam = True)

0: fid: 0.354, c: 0.105
1: fid: 0.367, c: 0.109
2: fid: 0.396, c: 0.114
3: fid: 0.436, c: 0.120
4: fid: 0.404, c: 0.125
5: fid: 0.506, c: 0.130
6: fid: 0.478, c: 0.136
7: fid: 0.411, c: 0.142
8: fid: 0.421, c: 0.148
9: fid: 0.490, c: 0.155
10: fid: 0.435, c: 0.162
11: fid: 0.434, c: 0.169
12: fid: 0.459, c: 0.176
13: fid: 0.521, c: 0.184
14: fid: 0.480, c: 0.191
15: fid: 0.491, c: 0.199
16: fid: 0.480, c: 0.208
17: fid: 0.504, c: 0.216
18: fid: 0.561, c: 0.225
19: fid: 0.557, c: 0.234
20: fid: 0.502, c: 0.244
21: fid: 0.545, c: 0.254
22: fid: 0.583, c: 0.264
23: fid: 0.529, c: 0.274
24: fid: 0.546, c: 0.284
25: fid: 0.544, c: 0.295
26: fid: 0.540, c: 0.306
27: fid: 0.541, c: 0.318
28: fid: 0.585, c: 0.329
29: fid: 0.601, c: 0.341
30: fid: 0.570, c: 0.353
31: fid: 0.626, c: 0.365
32: fid: 0.632, c: 0.377
33: fid: 0.675, c: 0.390
34: fid: 0.628, c: 0.402
35: fid: 0.665, c: 0.414
36: fid: 0.640, c: 0.427
37: fid: 0.657, c: 0.439
38: fid: 0.720, c: 0.452
39: fid: 0.669, c: 0.464
40: fid: 0

320: fid: 0.872, c: 0.936
321: fid: 0.881, c: 0.936
322: fid: 0.868, c: 0.936
323: fid: 0.876, c: 0.935
324: fid: 0.874, c: 0.935
325: fid: 0.888, c: 0.935
326: fid: 0.878, c: 0.935
327: fid: 0.870, c: 0.935
328: fid: 0.884, c: 0.934
329: fid: 0.871, c: 0.934
330: fid: 0.881, c: 0.934
331: fid: 0.868, c: 0.934
332: fid: 0.890, c: 0.934
333: fid: 0.876, c: 0.933
334: fid: 0.888, c: 0.933
335: fid: 0.857, c: 0.933
336: fid: 0.884, c: 0.933
337: fid: 0.895, c: 0.933
338: fid: 0.890, c: 0.932
339: fid: 0.909, c: 0.932
340: fid: 0.872, c: 0.932
341: fid: 0.873, c: 0.931
342: fid: 0.885, c: 0.931
343: fid: 0.872, c: 0.931
344: fid: 0.881, c: 0.931
345: fid: 0.869, c: 0.931
346: fid: 0.889, c: 0.930
347: fid: 0.851, c: 0.930
348: fid: 0.871, c: 0.930
349: fid: 0.886, c: 0.930
350: fid: 0.878, c: 0.930
351: fid: 0.885, c: 0.929
352: fid: 0.885, c: 0.929
353: fid: 0.889, c: 0.929
354: fid: 0.883, c: 0.929
355: fid: 0.862, c: 0.928
356: fid: 0.903, c: 0.928
357: fid: 0.883, c: 0.928
358: fid: 0.

636: fid: 0.942, c: 0.767
637: fid: 0.942, c: 0.767
638: fid: 0.954, c: 0.768
639: fid: 0.975, c: 0.769
640: fid: 0.968, c: 0.769
641: fid: 0.960, c: 0.769
642: fid: 0.980, c: 0.769
643: fid: 0.937, c: 0.770
644: fid: 0.963, c: 0.770
645: fid: 0.929, c: 0.770
646: fid: 0.957, c: 0.771
647: fid: 0.941, c: 0.771
648: fid: 0.957, c: 0.771
649: fid: 0.962, c: 0.772
650: fid: 0.968, c: 0.772
651: fid: 0.970, c: 0.771
652: fid: 0.987, c: 0.771
653: fid: 0.931, c: 0.771
654: fid: 0.985, c: 0.771
655: fid: 0.966, c: 0.770
656: fid: 0.956, c: 0.770
657: fid: 0.953, c: 0.769
658: fid: 0.982, c: 0.769
659: fid: 0.973, c: 0.768
660: fid: 0.955, c: 0.767
661: fid: 0.977, c: 0.767
662: fid: 0.956, c: 0.766
663: fid: 0.947, c: 0.765
664: fid: 0.952, c: 0.765
665: fid: 0.974, c: 0.765
666: fid: 0.984, c: 0.764
667: fid: 0.968, c: 0.763
668: fid: 0.957, c: 0.762
669: fid: 0.961, c: 0.762
670: fid: 0.970, c: 0.761
671: fid: 0.970, c: 0.760
672: fid: 0.963, c: 0.759
673: fid: 0.958, c: 0.759
674: fid: 0.

952: fid: 0.996, c: 0.715
953: fid: 0.985, c: 0.715
954: fid: 0.993, c: 0.715
955: fid: 0.994, c: 0.715
956: fid: 0.985, c: 0.715
957: fid: 0.993, c: 0.715
958: fid: 0.989, c: 0.715
959: fid: 0.992, c: 0.715
960: fid: 0.989, c: 0.715
961: fid: 0.990, c: 0.715
962: fid: 0.991, c: 0.715
963: fid: 0.992, c: 0.715
964: fid: 0.992, c: 0.715
965: fid: 0.988, c: 0.715
966: fid: 0.993, c: 0.715
967: fid: 0.994, c: 0.715
968: fid: 0.982, c: 0.715
969: fid: 0.995, c: 0.715
970: fid: 0.993, c: 0.714
971: fid: 0.994, c: 0.714
972: fid: 0.993, c: 0.714
973: fid: 0.993, c: 0.714
974: fid: 0.996, c: 0.714
975: fid: 0.997, c: 0.713
976: fid: 0.997, c: 0.713
977: fid: 0.987, c: 0.713
978: fid: 0.996, c: 0.712
979: fid: 0.991, c: 0.712
980: fid: 0.984, c: 0.712
981: fid: 0.994, c: 0.712
982: fid: 0.995, c: 0.712
983: fid: 0.995, c: 0.711
984: fid: 0.992, c: 0.711
985: fid: 0.996, c: 0.711
986: fid: 0.994, c: 0.711
987: fid: 0.986, c: 0.710
988: fid: 0.994, c: 0.710
989: fid: 0.997, c: 0.710
990: fid: 0.

1258: fid: 0.998, c: 0.703
1259: fid: 0.997, c: 0.703
1260: fid: 0.999, c: 0.703
1261: fid: 0.998, c: 0.703
1262: fid: 0.999, c: 0.703
1263: fid: 0.998, c: 0.703
1264: fid: 0.998, c: 0.703
1265: fid: 0.999, c: 0.702
1266: fid: 0.998, c: 0.702
1267: fid: 0.998, c: 0.702
1268: fid: 0.998, c: 0.702
1269: fid: 0.997, c: 0.702
1270: fid: 0.999, c: 0.702
1271: fid: 0.999, c: 0.702
1272: fid: 0.998, c: 0.702
1273: fid: 0.999, c: 0.702
1274: fid: 1.000, c: 0.702
1275: fid: 0.999, c: 0.702
1276: fid: 0.999, c: 0.702
1277: fid: 0.998, c: 0.702
1278: fid: 0.998, c: 0.702
1279: fid: 0.997, c: 0.702
1280: fid: 0.998, c: 0.703
1281: fid: 0.999, c: 0.703
1282: fid: 0.999, c: 0.703
1283: fid: 0.998, c: 0.703
1284: fid: 0.999, c: 0.703
1285: fid: 1.000, c: 0.703
1286: fid: 0.999, c: 0.703
1287: fid: 0.999, c: 0.703
1288: fid: 0.998, c: 0.703
1289: fid: 0.998, c: 0.703
1290: fid: 0.999, c: 0.703
1291: fid: 0.998, c: 0.703
1292: fid: 0.998, c: 0.703
1293: fid: 0.997, c: 0.703
1294: fid: 0.997, c: 0.703
1

1562: fid: 0.999, c: 0.701
1563: fid: 0.999, c: 0.701
1564: fid: 0.999, c: 0.701
1565: fid: 1.000, c: 0.701
1566: fid: 0.999, c: 0.701
1567: fid: 0.999, c: 0.701
1568: fid: 0.999, c: 0.701
1569: fid: 0.999, c: 0.701
1570: fid: 1.000, c: 0.701
1571: fid: 0.999, c: 0.701
1572: fid: 1.000, c: 0.701
1573: fid: 0.999, c: 0.701
1574: fid: 1.000, c: 0.701
1575: fid: 0.999, c: 0.701
1576: fid: 0.999, c: 0.701
1577: fid: 1.000, c: 0.701
1578: fid: 0.999, c: 0.701
1579: fid: 0.999, c: 0.701
1580: fid: 0.999, c: 0.701
1581: fid: 0.999, c: 0.701
1582: fid: 1.000, c: 0.701
1583: fid: 1.000, c: 0.701
1584: fid: 1.000, c: 0.701
1585: fid: 1.000, c: 0.701
1586: fid: 1.000, c: 0.701
1587: fid: 0.999, c: 0.701
1588: fid: 1.000, c: 0.701
1589: fid: 1.000, c: 0.701
1590: fid: 1.000, c: 0.701
1591: fid: 1.000, c: 0.701
1592: fid: 1.000, c: 0.701
1593: fid: 0.999, c: 0.701
1594: fid: 1.000, c: 0.701
1595: fid: 1.000, c: 0.701
1596: fid: 0.999, c: 0.701
1597: fid: 1.000, c: 0.701
1598: fid: 0.999, c: 0.701
1

1866: fid: 1.000, c: 0.701
1867: fid: 1.000, c: 0.701
1868: fid: 1.000, c: 0.701
1869: fid: 1.000, c: 0.701
1870: fid: 1.000, c: 0.701
1871: fid: 1.000, c: 0.701
1872: fid: 1.000, c: 0.701
1873: fid: 1.000, c: 0.701
1874: fid: 1.000, c: 0.701
1875: fid: 0.999, c: 0.701
1876: fid: 1.000, c: 0.701
1877: fid: 1.000, c: 0.701
1878: fid: 1.000, c: 0.701
1879: fid: 1.000, c: 0.701
1880: fid: 1.000, c: 0.701
1881: fid: 1.000, c: 0.701
1882: fid: 1.000, c: 0.701
1883: fid: 1.000, c: 0.701
1884: fid: 1.000, c: 0.701
1885: fid: 1.000, c: 0.701
1886: fid: 1.000, c: 0.701
1887: fid: 1.000, c: 0.700
1888: fid: 1.000, c: 0.700
1889: fid: 1.000, c: 0.700
1890: fid: 1.000, c: 0.700
1891: fid: 1.000, c: 0.700
1892: fid: 1.000, c: 0.700
1893: fid: 0.999, c: 0.700
1894: fid: 1.000, c: 0.700
1895: fid: 1.000, c: 0.700
1896: fid: 1.000, c: 0.700
1897: fid: 1.000, c: 0.700
1898: fid: 1.000, c: 0.700
1899: fid: 1.000, c: 0.700
1900: fid: 1.000, c: 0.701
1901: fid: 0.999, c: 0.701
1902: fid: 1.000, c: 0.701
1

In [8]:
n = 5
d = 2**n
rank = 6

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
X = generate_ginibre(d, d)
U = generate_unitary(X)
kraus_target = KrausMap(U, 0.7, d, rank)
kraus_model = KrausMap(U, 0.1, d, rank)

state_target_list = [kraus_target.apply_map(state_input) for state_input in state_input_list]

model4 = ModelQuantumMap(model = kraus_model,
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model4.train(num_iter = 2000, 
             use_adam = True)

0: fid: 0.480, c: 0.105
1: fid: 0.487, c: 0.109
2: fid: 0.491, c: 0.114
3: fid: 0.454, c: 0.120
4: fid: 0.505, c: 0.125
5: fid: 0.514, c: 0.131
6: fid: 0.508, c: 0.136
7: fid: 0.538, c: 0.142
8: fid: 0.547, c: 0.149
9: fid: 0.539, c: 0.155
10: fid: 0.527, c: 0.162
11: fid: 0.554, c: 0.169
12: fid: 0.552, c: 0.176
13: fid: 0.541, c: 0.183
14: fid: 0.591, c: 0.191
15: fid: 0.580, c: 0.199
16: fid: 0.584, c: 0.207
17: fid: 0.584, c: 0.216
18: fid: 0.601, c: 0.225
19: fid: 0.610, c: 0.234
20: fid: 0.607, c: 0.243
21: fid: 0.609, c: 0.253
22: fid: 0.640, c: 0.263
23: fid: 0.630, c: 0.273
24: fid: 0.638, c: 0.284
25: fid: 0.624, c: 0.294
26: fid: 0.613, c: 0.305
27: fid: 0.654, c: 0.317
28: fid: 0.635, c: 0.328
29: fid: 0.651, c: 0.340
30: fid: 0.685, c: 0.352
31: fid: 0.669, c: 0.364
32: fid: 0.682, c: 0.376
33: fid: 0.736, c: 0.389
34: fid: 0.727, c: 0.401
35: fid: 0.698, c: 0.414
36: fid: 0.705, c: 0.426
37: fid: 0.732, c: 0.439
38: fid: 0.702, c: 0.452
39: fid: 0.723, c: 0.464
40: fid: 0

320: fid: 0.907, c: 0.898
321: fid: 0.896, c: 0.897
322: fid: 0.899, c: 0.897
323: fid: 0.896, c: 0.896
324: fid: 0.909, c: 0.896
325: fid: 0.900, c: 0.895
326: fid: 0.895, c: 0.895
327: fid: 0.882, c: 0.894
328: fid: 0.876, c: 0.894
329: fid: 0.896, c: 0.894
330: fid: 0.896, c: 0.893
331: fid: 0.892, c: 0.893
332: fid: 0.883, c: 0.893
333: fid: 0.890, c: 0.893
334: fid: 0.896, c: 0.892
335: fid: 0.901, c: 0.892
336: fid: 0.887, c: 0.892
337: fid: 0.899, c: 0.891
338: fid: 0.885, c: 0.891
339: fid: 0.911, c: 0.891
340: fid: 0.898, c: 0.891
341: fid: 0.895, c: 0.890
342: fid: 0.896, c: 0.890
343: fid: 0.890, c: 0.890
344: fid: 0.890, c: 0.889
345: fid: 0.914, c: 0.889
346: fid: 0.903, c: 0.889
347: fid: 0.888, c: 0.888
348: fid: 0.884, c: 0.888
349: fid: 0.897, c: 0.888
350: fid: 0.892, c: 0.888
351: fid: 0.900, c: 0.887
352: fid: 0.907, c: 0.887
353: fid: 0.899, c: 0.887
354: fid: 0.890, c: 0.886
355: fid: 0.897, c: 0.886
356: fid: 0.895, c: 0.886
357: fid: 0.903, c: 0.886
358: fid: 0.

636: fid: 0.966, c: 0.765
637: fid: 0.972, c: 0.765
638: fid: 0.968, c: 0.764
639: fid: 0.958, c: 0.764
640: fid: 0.979, c: 0.763
641: fid: 0.959, c: 0.763
642: fid: 0.972, c: 0.762
643: fid: 0.967, c: 0.762
644: fid: 0.964, c: 0.761
645: fid: 0.961, c: 0.760
646: fid: 0.965, c: 0.760
647: fid: 0.957, c: 0.759
648: fid: 0.979, c: 0.759
649: fid: 0.962, c: 0.758
650: fid: 0.958, c: 0.758
651: fid: 0.948, c: 0.758
652: fid: 0.970, c: 0.757
653: fid: 0.965, c: 0.757
654: fid: 0.971, c: 0.757
655: fid: 0.968, c: 0.756
656: fid: 0.965, c: 0.756
657: fid: 0.957, c: 0.756
658: fid: 0.972, c: 0.756
659: fid: 0.962, c: 0.755
660: fid: 0.962, c: 0.755
661: fid: 0.956, c: 0.755
662: fid: 0.958, c: 0.755
663: fid: 0.974, c: 0.755
664: fid: 0.976, c: 0.755
665: fid: 0.964, c: 0.755
666: fid: 0.978, c: 0.755
667: fid: 0.965, c: 0.755
668: fid: 0.951, c: 0.755
669: fid: 0.966, c: 0.755
670: fid: 0.963, c: 0.755
671: fid: 0.950, c: 0.755
672: fid: 0.939, c: 0.755
673: fid: 0.962, c: 0.756
674: fid: 0.

952: fid: 0.995, c: 0.709
953: fid: 0.991, c: 0.709
954: fid: 0.992, c: 0.709
955: fid: 0.994, c: 0.709
956: fid: 0.996, c: 0.709
957: fid: 0.995, c: 0.709
958: fid: 0.993, c: 0.709
959: fid: 0.995, c: 0.709
960: fid: 0.995, c: 0.709
961: fid: 0.994, c: 0.709
962: fid: 0.996, c: 0.709
963: fid: 0.995, c: 0.708
964: fid: 0.993, c: 0.708
965: fid: 0.995, c: 0.708
966: fid: 0.996, c: 0.708
967: fid: 0.995, c: 0.708
968: fid: 0.996, c: 0.708
969: fid: 0.997, c: 0.708
970: fid: 0.997, c: 0.707
971: fid: 0.996, c: 0.707
972: fid: 0.997, c: 0.707
973: fid: 0.994, c: 0.707
974: fid: 0.993, c: 0.707
975: fid: 0.993, c: 0.707
976: fid: 0.997, c: 0.707
977: fid: 0.993, c: 0.707
978: fid: 0.997, c: 0.707
979: fid: 0.997, c: 0.707
980: fid: 0.996, c: 0.707
981: fid: 0.994, c: 0.707
982: fid: 0.993, c: 0.707
983: fid: 0.997, c: 0.707
984: fid: 0.992, c: 0.707
985: fid: 0.996, c: 0.707
986: fid: 0.991, c: 0.707
987: fid: 0.997, c: 0.707
988: fid: 0.997, c: 0.707
989: fid: 0.996, c: 0.707
990: fid: 0.

KeyboardInterrupt: 

### Choi Kraus Mix

In [ ]:
n = 3
d = 2**n
rank = 2

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
X = generate_ginibre(d, d)
U = generate_unitary(X)
kraus_target = ChoiMap(d, rank)
kraus_model = KrausMap(U, 0.1, d, rank)

state_target_list = [kraus_target.apply_map(state_input) for state_input in state_input_list]

model5 = ModelQuantumMap(model = kraus_model,
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model5.train(num_iter = 2000, 
             use_adam = True)

In [6]:
n = 3
d = 2**n
rank = 2

state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

np.random.seed(42)
X = generate_ginibre(d, d)
U = generate_unitary(X)
kraus_target = KrausMap(U, 0.5, d, rank)
kraus_model = ChoiMap(d, rank+1)

state_target_list = [kraus_target.apply_map(state_input) for state_input in state_input_list]

model6 = ModelQuantumMap(model = kraus_model,
                         state_input_list = state_input_list,
                         state_target_list = state_target_list,
                         lr = 0.05, 
                         h = 1e-4)

model6.train(num_iter = 2000, 
             use_adam = True)

0: fid: 0.570, c: 0.000
1: fid: 0.477, c: 0.000
2: fid: 0.543, c: 0.000
3: fid: 0.413, c: 0.000
4: fid: 0.572, c: 0.000
5: fid: 0.437, c: 0.000
6: fid: 0.445, c: 0.000
7: fid: 0.486, c: 0.000
8: fid: 0.410, c: 0.000
9: fid: 0.524, c: 0.000
10: fid: 0.397, c: 0.000
11: fid: 0.408, c: 0.000
12: fid: 0.517, c: 0.000
13: fid: 0.459, c: 0.000
14: fid: 0.547, c: 0.000
15: fid: 0.598, c: 0.000
16: fid: 0.556, c: 0.000
17: fid: 0.584, c: 0.000
18: fid: 0.595, c: 0.000
19: fid: 0.556, c: 0.000
20: fid: 0.463, c: 0.000
21: fid: 0.667, c: 0.000
22: fid: 0.557, c: 0.000
23: fid: 0.506, c: 0.000
24: fid: 0.586, c: 0.000
25: fid: 0.596, c: 0.000
26: fid: 0.549, c: 0.000
27: fid: 0.707, c: 0.000
28: fid: 0.629, c: 0.000
29: fid: 0.522, c: 0.000
30: fid: 0.497, c: 0.000
31: fid: 0.662, c: 0.000
32: fid: 0.535, c: 0.000
33: fid: 0.588, c: 0.000
34: fid: 0.574, c: 0.000
35: fid: 0.530, c: 0.000
36: fid: 0.702, c: 0.000
37: fid: 0.567, c: 0.000
38: fid: 0.570, c: 0.000
39: fid: 0.601, c: 0.000
40: fid: 0

320: fid: 0.991, c: 0.000
321: fid: 0.995, c: 0.000
322: fid: 0.990, c: 0.000
323: fid: 0.992, c: 0.000
324: fid: 0.989, c: 0.000
325: fid: 0.988, c: 0.000
326: fid: 0.992, c: 0.000
327: fid: 0.989, c: 0.000
328: fid: 0.992, c: 0.000
329: fid: 0.995, c: 0.000
330: fid: 0.988, c: 0.000
331: fid: 0.990, c: 0.000
332: fid: 0.994, c: 0.000
333: fid: 0.990, c: 0.000
334: fid: 0.993, c: 0.000
335: fid: 0.990, c: 0.000
336: fid: 0.988, c: 0.000
337: fid: 0.993, c: 0.000
338: fid: 0.992, c: 0.000
339: fid: 0.990, c: 0.000
340: fid: 0.987, c: 0.000
341: fid: 0.989, c: 0.000
342: fid: 0.995, c: 0.000
343: fid: 0.991, c: 0.000
344: fid: 0.992, c: 0.000
345: fid: 0.991, c: 0.000
346: fid: 0.991, c: 0.000
347: fid: 0.992, c: 0.000
348: fid: 0.995, c: 0.000
349: fid: 0.992, c: 0.000
350: fid: 0.991, c: 0.000
351: fid: 0.995, c: 0.000
352: fid: 0.992, c: 0.000
353: fid: 0.996, c: 0.000
354: fid: 0.991, c: 0.000
355: fid: 0.996, c: 0.000
356: fid: 0.995, c: 0.000
357: fid: 0.993, c: 0.000
358: fid: 0.

636: fid: 1.000, c: 0.000
637: fid: 1.000, c: 0.000
638: fid: 1.000, c: 0.000
639: fid: 1.000, c: 0.000
640: fid: 1.000, c: 0.000
641: fid: 1.000, c: 0.000
642: fid: 1.000, c: 0.000
643: fid: 1.000, c: 0.000
644: fid: 1.000, c: 0.000
645: fid: 1.000, c: 0.000
646: fid: 1.000, c: 0.000
647: fid: 1.000, c: 0.000
648: fid: 1.000, c: 0.000
649: fid: 1.000, c: 0.000
650: fid: 1.000, c: 0.000
651: fid: 1.000, c: 0.000
652: fid: 1.000, c: 0.000
653: fid: 1.000, c: 0.000
654: fid: 1.000, c: 0.000
655: fid: 1.000, c: 0.000
656: fid: 1.000, c: 0.000
657: fid: 1.000, c: 0.000
658: fid: 1.000, c: 0.000
659: fid: 1.000, c: 0.000
660: fid: 1.000, c: 0.000
661: fid: 1.000, c: 0.000
662: fid: 1.000, c: 0.000
663: fid: 1.000, c: 0.000
664: fid: 1.000, c: 0.000
665: fid: 1.000, c: 0.000
666: fid: 1.000, c: 0.000
667: fid: 1.000, c: 0.000
668: fid: 1.000, c: 0.000
669: fid: 1.000, c: 0.000
670: fid: 1.000, c: 0.000
671: fid: 1.000, c: 0.000
672: fid: 1.000, c: 0.000
673: fid: 1.000, c: 0.000
674: fid: 1.

952: fid: 1.000, c: 0.000
953: fid: 1.000, c: 0.000
954: fid: 1.000, c: 0.000
955: fid: 1.000, c: 0.000
956: fid: 1.000, c: 0.000
957: fid: 1.000, c: 0.000
958: fid: 1.000, c: 0.000
959: fid: 1.000, c: 0.000
960: fid: 1.000, c: 0.000
961: fid: 1.000, c: 0.000
962: fid: 1.000, c: 0.000
963: fid: 1.000, c: 0.000
964: fid: 1.000, c: 0.000
965: fid: 1.000, c: 0.000
966: fid: 1.000, c: 0.000
967: fid: 1.000, c: 0.000
968: fid: 1.000, c: 0.000
969: fid: 1.000, c: 0.000
970: fid: 1.000, c: 0.000
971: fid: 1.000, c: 0.000
972: fid: 1.000, c: 0.000
973: fid: 1.000, c: 0.000
974: fid: 1.000, c: 0.000
975: fid: 1.000, c: 0.000
976: fid: 1.000, c: 0.000
977: fid: 1.000, c: 0.000
978: fid: 1.000, c: 0.000
979: fid: 1.000, c: 0.000
980: fid: 1.000, c: 0.000
981: fid: 1.000, c: 0.000
982: fid: 1.000, c: 0.000
983: fid: 1.000, c: 0.000
984: fid: 1.000, c: 0.000
985: fid: 1.000, c: 0.000
986: fid: 1.000, c: 0.000
987: fid: 1.000, c: 0.000
988: fid: 1.000, c: 0.000
989: fid: 1.000, c: 0.000
990: fid: 1.

1258: fid: 1.000, c: 0.000
1259: fid: 1.000, c: 0.000
1260: fid: 1.000, c: 0.000
1261: fid: 1.000, c: 0.000
1262: fid: 1.000, c: 0.000
1263: fid: 1.000, c: 0.000
1264: fid: 1.000, c: 0.000
1265: fid: 1.000, c: 0.000
1266: fid: 1.000, c: 0.000
1267: fid: 1.000, c: 0.000
1268: fid: 1.000, c: 0.000
1269: fid: 1.000, c: 0.000
1270: fid: 1.000, c: 0.000
1271: fid: 1.000, c: 0.000
1272: fid: 1.000, c: 0.000
1273: fid: 1.000, c: 0.000
1274: fid: 1.000, c: 0.000
1275: fid: 1.000, c: 0.000
1276: fid: 1.000, c: 0.000
1277: fid: 1.000, c: 0.000
1278: fid: 1.000, c: 0.000
1279: fid: 1.000, c: 0.000
1280: fid: 1.000, c: 0.000
1281: fid: 1.000, c: 0.000
1282: fid: 1.000, c: 0.000
1283: fid: 1.000, c: 0.000
1284: fid: 1.000, c: 0.000
1285: fid: 1.000, c: 0.000
1286: fid: 1.000, c: 0.000
1287: fid: 1.000, c: 0.000
1288: fid: 1.000, c: 0.000
1289: fid: 1.000, c: 0.000
1290: fid: 1.000, c: 0.000
1291: fid: 1.000, c: 0.000
1292: fid: 1.000, c: 0.000
1293: fid: 1.000, c: 0.000
1294: fid: 1.000, c: 0.000
1

1562: fid: 1.000, c: 0.000
1563: fid: 1.000, c: 0.000
1564: fid: 1.000, c: 0.000
1565: fid: 1.000, c: 0.000
1566: fid: 1.000, c: 0.000
1567: fid: 1.000, c: 0.000
1568: fid: 1.000, c: 0.000
1569: fid: 1.000, c: 0.000
1570: fid: 1.000, c: 0.000
1571: fid: 1.000, c: 0.000
1572: fid: 1.000, c: 0.000
1573: fid: 1.000, c: 0.000
1574: fid: 1.000, c: 0.000
1575: fid: 1.000, c: 0.000
1576: fid: 1.000, c: 0.000
1577: fid: 1.000, c: 0.000
1578: fid: 1.000, c: 0.000
1579: fid: 1.000, c: 0.000
1580: fid: 1.000, c: 0.000
1581: fid: 1.000, c: 0.000
1582: fid: 1.000, c: 0.000
1583: fid: 1.000, c: 0.000
1584: fid: 1.000, c: 0.000
1585: fid: 1.000, c: 0.000
1586: fid: 1.000, c: 0.000
1587: fid: 1.000, c: 0.000
1588: fid: 1.000, c: 0.000
1589: fid: 1.000, c: 0.000
1590: fid: 1.000, c: 0.000
1591: fid: 1.000, c: 0.000
1592: fid: 1.000, c: 0.000
1593: fid: 1.000, c: 0.000
1594: fid: 1.000, c: 0.000
1595: fid: 1.000, c: 0.000
1596: fid: 1.000, c: 0.000
1597: fid: 1.000, c: 0.000
1598: fid: 1.000, c: 0.000
1

1866: fid: 1.000, c: 0.000
1867: fid: 1.000, c: 0.000
1868: fid: 1.000, c: 0.000
1869: fid: 1.000, c: 0.000
1870: fid: 1.000, c: 0.000
1871: fid: 1.000, c: 0.000
1872: fid: 1.000, c: 0.000
1873: fid: 1.000, c: 0.000
1874: fid: 1.000, c: 0.000
1875: fid: 1.000, c: 0.000
1876: fid: 1.000, c: 0.000
1877: fid: 1.000, c: 0.000
1878: fid: 1.000, c: 0.000
1879: fid: 1.000, c: 0.000
1880: fid: 1.000, c: 0.000
1881: fid: 1.000, c: 0.000
1882: fid: 1.000, c: 0.000
1883: fid: 1.000, c: 0.000
1884: fid: 1.000, c: 0.000
1885: fid: 1.000, c: 0.000
1886: fid: 1.000, c: 0.000
1887: fid: 1.000, c: 0.000
1888: fid: 1.000, c: 0.000
1889: fid: 1.000, c: 0.000
1890: fid: 1.000, c: 0.000
1891: fid: 1.000, c: 0.000
1892: fid: 1.000, c: 0.000
1893: fid: 1.000, c: 0.000
1894: fid: 1.000, c: 0.000
1895: fid: 1.000, c: 0.000
1896: fid: 1.000, c: 0.000
1897: fid: 1.000, c: 0.000
1898: fid: 1.000, c: 0.000
1899: fid: 1.000, c: 0.000
1900: fid: 1.000, c: 0.000
1901: fid: 1.000, c: 0.000
1902: fid: 1.000, c: 0.000
1

## Pauli String Data

In [6]:
n = 2
d = 2**n
rank = 2
num_samples = 10000

np.random.seed(42)
state_input_list = [prepare_input(numberToBase(i, 6, n)) for i in range(6**n)]

choi_target = ChoiMap(d, rank)
state_target_list = [choi_target.apply_map(state_input) for state_input in state_input_list]

data = np.zeros((6**n, 6**n, d))

for i in tqdm(range(num_samples)):   
    idx1 = np.random.randint(6**n)
    state = state_target_list[idx1]
    idx2 = np.random.randint(6**n)
    basis = prepare_input(numberToBase(idx2, 6, n), return_unitary = True)
    idx3 = sample_bitstring(state, basis, return_index = True)
    data[idx1, idx2, idx3] += 1

In [7]:
print(data)

[[[ 3.  0.  5.  0.]
  [ 3.  1.  0.  1.]
  [ 8.  3.  2.  1.]
  [ 6.  0.  0.  4.]
  [ 4.  1.  4.  2.]
  [ 6.  0.  0.  0.]
  [ 1.  2.  3.  5.]
  [ 3.  4.  1.  2.]
  [ 0.  5.  1.  1.]
  [ 0.  3.  2.  1.]
  [ 0.  6.  0.  1.]
  [ 1.  4.  1.  0.]
  [ 1.  1.  1.  0.]
  [ 1.  1.  0.  0.]
  [ 3.  2.  0.  0.]
  [ 1.  3.  1.  0.]
  [ 4.  1.  1.  1.]
  [ 1.  0.  0.  0.]
  [ 1.  4.  6.  3.]
  [ 4.  1.  0.  1.]
  [ 3.  1.  0.  2.]
  [ 0.  1.  0.  3.]
  [ 2.  2.  0.  2.]
  [ 2.  1.  0.  1.]
  [ 1.  1.  3.  3.]
  [ 4.  1.  0.  4.]
  [ 1.  1.  2.  1.]
  [ 3.  1.  0.  0.]
  [ 2.  2.  3.  3.]
  [ 4.  2.  1.  3.]
  [ 0.  1.  1.  1.]
  [ 6.  3.  0.  2.]
  [ 3.  1.  1.  1.]
  [ 5.  0.  2.  2.]
  [ 8.  0.  0.  2.]
  [ 4.  4.  1.  3.]]

 [[ 4.  2.  0.  0.]
  [ 1.  1.  2.  5.]
  [ 0.  3.  4.  1.]
  [ 4.  6.  2.  0.]
  [ 3.  3.  3.  0.]
  [ 1.  2.  2.  0.]
  [ 2.  2.  2.  0.]
  [ 1.  0.  3.  2.]
  [ 4.  3.  1.  1.]
  [ 3.  3.  1.  1.]
  [ 0.  1.  2.  1.]
  [ 3.  2.  0.  4.]
  [ 3.  3.  2.  1.]
  [ 2.  0.  4.  2.