In [2]:
import numpy as np
import qiskit as qk
import matplotlib.pyplot as plt
import multiprocessing as mp
from qiskit.quantum_info import DensityMatrix
from qiskit.quantum_info import Operator
from scipy.linalg import sqrtm
from tqdm.notebook import tqdm

from src import *

np.set_printoptions(precision=2)

In [3]:
np.random.seed(42)
state_random = generate_state(2**2, 1)
print(state_random)
print(partial_trace(state_random))

[[ 0.05+0.j   -0.  +0.02j -0.01-0.15j  0.09-0.12j]
 [-0.  -0.02j  0.01+0.j   -0.07+0.01j -0.06-0.04j]
 [-0.01+0.15j -0.07-0.01j  0.47+0.j    0.35+0.31j]
 [ 0.09+0.12j -0.06+0.04j  0.35-0.31j  0.47+0.j  ]]
[[0.52+0.j   0.35+0.33j]
 [0.35-0.33j 0.48+0.j  ]]


In [18]:
print(np.array(range(1,17)).reshape(4,4))
print(np.array(range(1,17)).reshape(4,4).reshape(2,2,2,2)[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
